### ISSUE TITLE
热身任务的CodeReview

### ISSUE THREAD

**Issue by ferry1227** [undefinedWebapp/undefined.github.io#3]
hi，小屯。
你刚提交的index.html，个人简介部分，图片没提交哦。然后alt未改过来。如图：
![1](https://cloud.githubusercontent.com/assets/7913724/8740274/33755fe8-2c79-11e5-8931-e185bb637ffa.png)

**Comment by liwenzhusdu** [comment]
已修改，提交的时候忘了，thank u
